export type LessonPlanSubCategory =
  | "Conversation Class"
  | "Speaking Class"
  | "Listening Class"
  | "Reading Class"
  | "Writing Class"
  | "Grammar Class"
  | "First Conditional"
  | "Second Conditional"
  | "Technology"
  | "Clothes / Fashion"
  | "Travel / Holidays"
  | "Films / Movies"
  | "Video"
  | "Role Play"
  | "A1"
  | "A2"
  | "B1"
  | "B2"
  | "C1"
  | "C2";
